[project]
name = 'backend'
version = '0.1.0'
description = '''
Backend for web app rating Russian subjects for IT specialists by qualification level 
using objective metrics
'''
readme = 'README.md'
authors = [
    { name = 'snogtev', email = 'stepannogtev2023@gmail.com' }
]
requires-python = '>=3.12'
dependencies = [
    'fastapi[standard]>=0.141.1',
    'pandas>=3.0.5',
    'scikit-learn>=1.9.1',
    'sqlmodel>=0.0.42',
]

[dependency-groups]
dev = [
    'ruff>=0.16.7',
]

[tool.uv]
managed = true
package = false

[tool.fastapi]
entrypoint = 'app.main:app'

[tool.ruff.lint.isort]
known-first-party = ['app', 'scripts']