from enum import Enum

from pydantic import model_validator
from sqlmodel import SQLModel


class Grade(str, Enum):
    APPLICANT = 'applicant'
    INTERN = 'intern'
    JUNIOR = 'junior'
    MIDDLE = 'middle'
    SENIOR = 'senior'

class District(str, Enum):
    CENTRAL = 'central'
    FAR_EASTERN = 'far-eastern'
    NORTH_CAUCASIAN = 'north-caucasian'
    NORTHWESTERN = 'northwestern'
    SIBERIAN = 'siberian'
    SOUTHERN = 'southern'
    URAL = 'ural'
    VOLGA = 'volga'

class Subject(str, Enum):
    REPUBLIC_OF_ADYGEA = 'republic-of-adygea'
    ALTAI_REPUBLIC = 'altai-republic'
    REPUBLIC_BASHKORTOSTAN = 'republic-of-bashkortostan'
    REPUBLIC_OF_BURYATIA = 'republic-of-buryatia'
    REPUBLIC_OF_DAGESTAN = 'republic-of-dagestan'
    DONETSK_PEOPLES_REPUBLIC = 'donetsk-peoples-republic'
    REPUBLIC_OF_INGUSHETIA = 'republic-of-ingushetia'
    KABARDINO_BALKAR_REPUBLIC = 'kabardino-balkar-republic'
    REPUBLIC_OF_KALMYKIA = 'republic-of-kalmykia'
    KARACHAY_CHERKESS_REPUBLIC = 'karachay-cherkess-republic'
    REPUBLIC_OF_KARELIA = 'republic-of-karelia'
    KOMI_REPUBLIC = 'komi-republic'
    REPUBLIC_OF_CRIMEA = 'republic-of-crimea'
    LUGANSK_PEOPLES_REPUBLIC = 'lugansk-peoples-republic'
    MARI_EL_REPUBLIC = 'mari-el-republic'
    REPUBLIC_OF_MORDOVIA = 'republic-of-mordovia'
    SAKHA_YAKUTIA_REPUBLIC = 'sakha-yakutia-republic'
    REPUBLIC_OF_NORTH_OSSETIA_ALANIA = 'republic-of-north-ossetia-alania'
    REPUBLIC_OF_TATARSTAN = 'republic-of-tatarstan'
    TUVA_REPUBLIC = 'tuva-republic'
    UDMURTS_REPUBLIC = 'udmurts-republic'
    REPUBLIC_OF_KHAKASSIA = 'republic-of-khakassia'
    CHECHEN_REPUBLIC = 'chechen-republic'
    CHUVASH_REPUBLIC = 'chuvash-republic'
    ALTAI_KRAI = 'altai-krai'
    ZABAYKALSKY_KRAY = 'zabaykalsky-kray'
    KAMCHATKA_KRAI = 'kamchatka-krai'
    KRASNODAR_KRAI = 'krasnodar-krai'
    KRASNOYARSK_KRAI = 'krasnoyarsk-krai'
    PERM_KRAI = 'perm-krai'
    PRIMORSKY_KRAI = 'primorsky-krai'
    STAVROPOL_KRAI = 'stavropol-krai'
    KHABAROVSK_KRAI = 'khabarovsk-krai'
    AMUR_OBLAST = 'amur-oblast'
    ARKHANGELSK_OBLAST = 'arkhangelsk-oblast'
    ASTRAKHAN_OBLAST = 'astrakhan-oblast'
    BELGOROD_OBLAST = 'belgorod-oblast'
    BRYANSK_OBLAST = 'bryansk-oblast'
    VLADIMIR_OBLAST = 'vladimir-oblast'
    VOLGOGRAD_OBLAST = 'volgograd-oblast'
    VOLOGDA_OBLAST = 'vologda-oblast'
    VORONEZH_OBLAST = 'voronezh-oblast'
    ZAPOROZHYE_OBLAST = 'zaporozhye-oblast'
    IVANOVO_OBLAST = 'ivanovo-oblast'
    IRKUTSK_OBLAST = 'irkutsk-oblast'
    KALININGRAD_OBLAST = 'kaliningrad-oblast'
    KALUGA_OBLAST = 'kaluga-oblast'
    KEMEROVO_OBLAST_KUZBASS = 'kemerovo-oblast-kuzbass'
    KIROV_OBLAST = 'kirov-oblast'
    KOSTROMA_OBLAST = 'kostroma-oblast'
    KURGAN_OBLAST = 'kurgan-oblast'
    KURSK_OBLAST = 'kursk-oblast'
    LENINGRAD_OBLAST = 'leningrad-oblast'
    LIPETSK_OBLAST = 'lipetsk-oblast'
    MAGADAN_OBLAST = 'magadan-oblast'
    MOSCOW_OBLAST = 'moscow-oblast'
    MURMANSK_OBLAST = 'murmansk-oblast'
    NIZHNY_NOVGOROD_OBLAST = 'nizhny-novgorod-oblast'
    NOVGOROD_OBLAST = 'novgorod-oblast'
    NOVOSIBIRSK_OBLAST = 'novosibirsk-oblast'
    OMSK_OBLAST = 'omsk-oblast'
    ORENBURG_OBLAST = 'orenburg-oblast'
    ORYOL_OBLAST = 'oryol-oblast'
    PENZA_OBLAST = 'penza-oblast'
    PSKOV_OBLAST = 'pskov-oblast'
    ROSTOV_OBLAST = 'rostov-oblast'
    RYAZAN_OBLAST = 'ryazan-oblast'
    SAMARA_OBLAST = 'samara-oblast'
    SARATOV_OBLAST = 'saratov-oblast'
    SAKHALIN_OBLAST = 'sakhalin-oblast'
    SVERDLOVSK_OBLAST = 'sverdlovsk-oblast'
    SMOLENSK_OBLAST = 'smolensk-oblast'
    TAMBOV_OBLAST = 'tambov-oblast'
    TVER_OBLAST = 'tver-oblast'
    TOMSK_OBLAST = 'tomsk-oblast'
    TULA_OBLAST = 'tula-oblast'
    TYUMEN_OBLAST = 'tyumen-oblast'
    ULYANOVSK_OBLAST = 'ulyanovsk-oblast'
    KHERSON_OBLAST = 'kherson-oblast'
    CHELYABINSK_OBLAST = 'chelyabinsk-oblast'
    YAROSLAVL_OBLAST = 'yaroslavl-oblast'
    MOSCOW_CITY = 'moscow-city'
    SAINT_PETERSBURG_CITY = 'saint-petersburg-city'
    SEVASTOPOL_CITY = 'sevastopol-city'
    JEWISH_AUTONOMOUS_OBLAST = 'jewish-autonomous-oblast'
    NENETS_AUTONOMOUS_OKRUG = 'nenets-autonomous-okrug'
    KHANTY_MANSI_AUTONOMOUS_OKRUG_YUGRA = 'khanty-mansi-autonomous-okrug-yugra'
    CHUKOTKA_AUTONOMOUS_OKRUG = 'chukotka-autonomous-okrug'
    YAMALO_NENETS_AUTONOMOUS_OKRUG = 'yamalo-nenets-autonomous-okrug'

class SubjectRequest(SQLModel):
    grade: Grade
    district: District | None = None
    subject: Subject | None = None

    @model_validator(mode='after')
    def check_it_benefits(self):
        if self.district is not None and self.subject:
            raise ValueError('Поиск возможен только по единственному фильтру.')
        return self